# This USB-powered dongle is the central for both wireless halves.
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_POINTING=y

# Preserve the familiar display layout and brightness on current Prospector.
CONFIG_PROSPECTOR_STATUS_SCREEN_CLASSIC=y
CONFIG_PROSPECTOR_MODIFIER_OS_WINDOWS=y
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=30
CONFIG_LV_DEF_REFR_PERIOD=30
